//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLeague.DataV2.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HoftwareEntities : DbContext
    {
        public HoftwareEntities()
            : base("name=HoftwareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ML_Game> ML_Game { get; set; }
        public virtual DbSet<ML_League> ML_League { get; set; }
        public virtual DbSet<ML_LeagueType> ML_LeagueType { get; set; }
        public virtual DbSet<ML_User> ML_User { get; set; }
        public virtual DbSet<ML_UserLeague> ML_UserLeague { get; set; }
    }
}
