//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLeague.DataV2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ML_League
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ML_League()
        {
            this.ML_Game = new HashSet<ML_Game>();
            this.ML_UserLeague = new HashSet<ML_UserLeague>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> LeagueTypeID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ML_Game> ML_Game { get; set; }
        public virtual ML_User ML_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ML_UserLeague> ML_UserLeague { get; set; }
        public virtual ML_LeagueType ML_LeagueType { get; set; }
    }
}
