//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLeague.DataV2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ML_UserLeague
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LeagueID { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Losses { get; set; }
        public Nullable<int> Ties { get; set; }
        public Nullable<int> PointsScored { get; set; }
        public Nullable<int> PointsAllowed { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ML_League ML_League { get; set; }
        public virtual ML_User ML_User { get; set; }
    }
}
