//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLeague.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int OpponentID { get; set; }
        public double UserScore { get; set; }
        public double OpponentScore { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public int LeagueID { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual UserLeague UserLeague { get; set; }
        public virtual UserLeague UserLeague1 { get; set; }
        public virtual League League { get; set; }
    }
}
