//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLeague.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueRequest
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int InviteeID { get; set; }
        public int LeagueID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsDecided { get; set; }
    }
}
