//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLeague.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityToken
    {
        public int ID { get; set; }
        public string SessionToken { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool isValid { get; set; }
    
        public virtual User User { get; set; }
    }
}
