//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLeague.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLeague
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int LeagueID { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Losses { get; set; }
        public Nullable<double> PointsScored { get; set; }
        public Nullable<double> PointsAllowed { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual League League { get; set; }
        public virtual User User { get; set; }
    }
}
